# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('mail_id', models.EmailField(max_length=300)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.IntegerField()),
            ],
        ),
    ]
