# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-27 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_auto_20170618_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameField(
            model_name='attendee',
            old_name='mobile_no',
            new_name='phoneNo',
        ),
        migrations.RemoveField(
            model_name='attendee',
            name='mail_id',
        ),
        migrations.AddField(
            model_name='attendee',
            name='age',
            field=models.IntegerField(default=9894945678),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='gender',
            field=models.CharField(default='Female', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='language',
            field=models.CharField(default='Python', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='mailId',
            field=models.EmailField(default='Raveena@5gindia.net', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendee',
            name='qualification',
            field=models.CharField(default='BE', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendee',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.Question'),
        ),
    ]
