# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendee',
            name='mail_id',
            field=models.EmailField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='attendee',
            name='mobile_no',
            field=models.IntegerField(unique=True),
        ),
    ]
